name: virtualLibraryAPI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup java
      uses: joschi/setup-jdk@v1
      with:
        java-version: 'openjdk11'
        architecture: 'x64'
    - name: Build with Maven and test
      run: mvn clean package test -P test
